import { InventoryItem } from '@/types'

export const MOCK_ITEMS: InventoryItem[] = [
  // --- VENDUS ---
  {
    id: 'v1',
    created_at: '2026-03-05T09:00:00Z',
    item_name: 'Nike Air Force 1 Low — T42',
    brand: 'Nike',
    purchase_price: 32,
    vinted_fees: 1.5,
    expected_sale_price: 65,
    actual_sale_price: 68,
    sale_fees: 2.8,
    boost_cost: 0,
    location: 'Chez Louis',
    status: 'Vendu',
    posted_at: null,
    sold_at: '2026-03-09T14:20:00Z',
    notes: null,
    category: 'Chaussure',
    size: '42',
  },
  {
    id: 'v2',
    created_at: '2026-03-07T11:00:00Z',
    item_name: "Levi's 501 — W32 L32",
    brand: "Levi's",
    purchase_price: 15,
    vinted_fees: 0.8,
    expected_sale_price: 38,
    actual_sale_price: 40,
    sale_fees: 1.6,
    boost_cost: 0,
    location: 'Chez Célian',
    status: 'Vendu',
    posted_at: null,
    sold_at: '2026-03-12T10:00:00Z',
    notes: null,
    category: 'Vêtement',
    size: 'W32 L32',
  },
  {
    id: 'v3',
    created_at: '2026-03-10T15:00:00Z',
    item_name: 'Carhartt Detroit Jacket — L',
    brand: 'Carhartt',
    purchase_price: 28,
    vinted_fees: 1.2,
    expected_sale_price: 70,
    actual_sale_price: 55,
    sale_fees: 2.2,
    boost_cost: 0,
    location: 'Chez Louis',
    status: 'Vendu',
    posted_at: null,
    sold_at: '2026-03-18T09:00:00Z',
    notes: 'Petite tache sur la manche, prix baissé',
    category: 'Vêtement',
    size: 'L',
  },
  {
    id: 'v4',
    created_at: '2026-03-14T13:00:00Z',
    item_name: 'Stone Island Sweat FW22 — M',
    brand: 'Stone Island',
    purchase_price: 42,
    vinted_fees: 2,
    expected_sale_price: 90,
    actual_sale_price: 88,
    sale_fees: 3.5,
    boost_cost: 0,
    location: 'Chez Célian',
    status: 'Vendu',
    posted_at: null,
    sold_at: '2026-03-22T16:00:00Z',
    notes: null,
    category: 'Vêtement',
    size: 'M',
  },
  // --- EN STOCK ---
  {
    id: 's1',
    created_at: '2026-03-20T10:00:00Z',
    item_name: 'Jordan 1 Mid Smoke Grey — T43',
    brand: 'Jordan',
    purchase_price: 58,
    vinted_fees: 2.5,
    expected_sale_price: 110,
    actual_sale_price: null,
    sale_fees: 0,
    boost_cost: 0,
    location: 'Chez Louis',
    status: 'En Stock',
    posted_at: null,
    sold_at: null,
    notes: null,
    category: 'Chaussure',
    size: '43',
  },
  {
    id: 's2',
    created_at: '2026-03-22T14:00:00Z',
    item_name: 'Ralph Lauren Bomber — L',
    brand: 'Ralph Lauren',
    purchase_price: 38,
    vinted_fees: 1.8,
    expected_sale_price: 85,
    actual_sale_price: null,
    sale_fees: 0,
    boost_cost: 0,
    location: 'Chez Célian',
    status: 'En Stock',
    posted_at: null,
    sold_at: null,
    notes: null,
    category: 'Vêtement',
    size: 'L',
  },
  {
    id: 's3',
    created_at: '2026-03-25T09:30:00Z',
    item_name: 'Lacoste Polo L.12.12 — T4',
    brand: 'Lacoste',
    purchase_price: 12,
    vinted_fees: 0.5,
    expected_sale_price: 28,
    actual_sale_price: null,
    sale_fees: 0,
    boost_cost: 0,
    location: 'Chez Célian',
    status: 'En Stock',
    posted_at: null,
    sold_at: null,
    notes: null,
    category: 'Vêtement',
    size: 'T4',
  },
  {
    id: 's4',
    created_at: '2026-03-28T11:00:00Z',
    item_name: 'New Balance 550 White Green — T41',
    brand: 'New Balance',
    purchase_price: 45,
    vinted_fees: 2,
    expected_sale_price: 95,
    actual_sale_price: null,
    sale_fees: 0,
    boost_cost: 0,
    location: 'Chez Louis',
    status: 'En Stock',
    posted_at: null,
    sold_at: null,
    notes: 'Box non-fournie',
    category: 'Chaussure',
    size: '41',
  },
]
